In [1]:
import pandas as pd

In [13]:
empresaA = pd.read_json('../data/raw/dados_empresaA.json')
empresaB = pd.read_csv('../data/raw/dados_empresaB.csv')

In [14]:
empresaA

,Nome do Produto,Categoria do Produto,Preço do Produto (R$),Quantidade em Estoque,Filial
0,Blush em pó,Eletrodomésticos,79.41,7,Filial 7
1,Lápis de sobrancelha,Eletrodomésticos,85.47,78,Filial 8
2,Base líquida,Roupas,75.02,34,Filial 8
3,Base líquida,Roupas,44.94,90,Filial 10
4,Lápis de sobrancelha,Alimentos,58.63,91,Filial 7
...,...,...,...,...,...
3118,Lápis de sobrancelha,Alimentos,91.77,5,Filial 2
3119,Pó compacto,Eletrodomésticos,43.46,43,Filial 3
3120,Lápis de sobrancelha,Roupas,63.69,7,Filial 3
3121,Lápis de sobrancelha,Eletrônicos,72.83,55,Filial 3
3122,Delineador líquido,Eletrônicos,64.68,48,Filial 8

In [15]:
empresaB

,Nome do Item,Classificação do Produto,Valor em Reais (R$),Quantidade em Estoque,Nome da Loja,Data da Venda
0,Lápis de sobrancelha,Roupas,55.17,62,Filial 1,2023-04-13 18:58:06.794203
1,Batom matte,Eletrônicos,74.15,48,Filial 9,2023-06-03 18:58:06.794203
2,Corretivo,Roupas,54.86,36,Filial 5,2023-06-08 18:58:06.794203
3,Delineador líquido,Roupas,91.29,1,Filial 8,2023-02-27 18:58:06.794203
4,Batom líquido,Roupas,44.65,52,Filial 2,2022-09-05 18:58:06.794203
...,...,...,...,...,...,...
1318,Lápis de sobrancelha,Alimentos,94.08,94,Filial 7,2022-11-20 18:58:06.794203
1319,Corretivo,Roupas,5.60,49,Filial 4,2023-07-16 18:58:06.794203
1320,Pó compacto,Eletrônicos,22.36,16,Filial 3,2023-01-24 18:58:06.794203
1321,Base líquida,Roupas,3.79,5,Filial 5,2022-12-18 18:58:06.794203
1322,Sombra de olhos,Eletrônicos,41.73,5,Filial 6,2022-11-21 18:58:06.794203

In [19]:
colunas_json = list(empresaA.columns)
colunas_json

['Nome do Produto',
 'Categoria do Produto',
 'Preço do Produto (R$)',
 'Quantidade em Estoque',
 'Filial']

In [20]:
colunas_csv = list(empresaB.columns)
colunas_csv

['Nome do Item',
 'Classificação do Produto',
 'Valor em Reais (R$)',
 'Quantidade em Estoque',
 'Nome da Loja',
 'Data da Venda']

In [22]:
key_mapping = {'Nome do Item': 'Nome do Produto',
                'Classificação do Produto': 'Categoria do Produto',
                'Valor em Reais (R$)': 'Preço do Produto (R$)',
                'Quantidade em Estoque': 'Quantidade em Estoque',
                'Nome da Loja': 'Filial',
                'Data da Venda': 'Data da Venda'}

In [23]:
empresaB = empresaB.rename(columns=key_mapping)

In [32]:
empresaA['Data da Venda'] = 'Indisponível'

In [34]:
df_final = pd.concat([empresaA, empresaB], ignore_index=True)

In [39]:
df_final.to_csv('../data/processed/dados_combinados.csv', index=False)